# Generated by Django 4.0.1 on 2022-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
    ]
