# Generated by Django 4.0.1 on 2022-05-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsstory_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(default='https://picsum.photos/536/354', max_length=200),
        ),
    ]
